# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [14]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [15]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(Path("Resources/applicants_data.csv"))
# Review the DataFrame
applicant_data_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [16]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [18]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(["EIN", "NAME"], axis = 1)
# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [19]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [20]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [21]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [22]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
)

# Review the DataFrame
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [24]:
# Create a DataFrame with the columnns containing numerical variables from the original dataset
numerical_variables_df = applicant_data_df.drop(columns = categorical_variables)

# Review the DataFrame
numerical_variables_df.head()

   STATUS  ASK_AMT  IS_SUCCESSFUL
0       1     5000              1
1       1   108590              1
2       1     5000              0
3       1     6692              1
4       1   142590              1

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [25]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat(
    [
        numerical_variables_df,
        encoded_df
    ],
    axis=1
)
# Review the Dataframe
encoded_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [26]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [27]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=["IS_SUCCESSFUL"])

# Review the features DataFrame
X

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [28]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [29]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [30]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [31]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [32]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + number_output_neurons) // 2 

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [33]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 + number_output_neurons) // 2 

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [34]:
# Create the Sequential model instance
nn = Sequential()

In [35]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [ ]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [36]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

In [37]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 58)                6786
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 59
=================================================================
Total params: 6,845
Trainable params: 6,845
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [38]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [39]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 710us/step - loss: 0.6072 - accuracy: 0.7061
Epoch 2/50
804/804 [==============================] - 1s 699us/step - loss: 0.5601 - accuracy: 0.7277
Epoch 3/50
804/804 [==============================] - 1s 712us/step - loss: 0.5517 - accuracy: 0.7279
Epoch 4/50
804/804 [==============================] - 1s 707us/step - loss: 0.5594 - accuracy: 0.7240
Epoch 5/50
804/804 [==============================] - 1s 713us/step - loss: 0.5480 - accuracy: 0.7317
Epoch 6/50
804/804 [==============================] - 1s 703us/step - loss: 0.5473 - accuracy: 0.7308
Epoch 7/50
804/804 [==============================] - 1s 707us/step - loss: 0.5450 - accuracy: 0.7334
Epoch 8/50
804/804 [==============================] - 1s 711us/step - loss: 0.5459 - accuracy: 0.7336
Epoch 9/50
804/804 [==============================] - 1s 710us/step - loss: 0.5453 - accuracy: 0.7332
Epoch 10/50
804/804 [==============================] - 1s 732us/step - loss: 0.5440 - accuracy: 0.7323
Epoch 11/50
804/804 [==============================] - 1s 901us/step - loss: 0.5493 - accuracy: 0.7297
Epoch 12/50
804/804 [==============================] - 1s 802us/step - loss: 0.5478 - accuracy: 0.7316
Epoch 13/50
804/804 [==============================] - 1s 834us/step - loss: 0.5446 - accuracy: 0.7293
Epoch 14/50
804/804 [==============================] - 1s 728us/step - loss: 0.5470 - accuracy: 0.7337
Epoch 15/50
804/804 [==============================] - 1s 728us/step - loss: 0.5426 - accuracy: 0.7351
Epoch 16/50
804/804 [==============================] - 1s 711us/step - loss: 0.5437 - accuracy: 0.7347
Epoch 17/50
804/804 [==============================] - 1s 716us/step - loss: 0.5442 - accuracy: 0.7360
Epoch 18/50
804/804 [==============================] - 1s 720us/step - loss: 0.5365 - accuracy: 0.7394
Epoch 19/50
804/804 [==============================] - 1s 722us/step - loss: 0.5385 - accuracy: 0.7360
Epoch 20/50
804/804 [==============================] - 1s 728us/step - loss: 0.5404 - accuracy: 0.7336
Epoch 21/50
804/804 [==============================] - 1s 728us/step - loss: 0.5428 - accuracy: 0.7325
Epoch 22/50
804/804 [==============================] - 1s 747us/step - loss: 0.5367 - accuracy: 0.7391
Epoch 23/50
804/804 [==============================] - 1s 725us/step - loss: 0.5434 - accuracy: 0.7312
Epoch 24/50
804/804 [==============================] - 1s 725us/step - loss: 0.5393 - accuracy: 0.7359
Epoch 25/50
804/804 [==============================] - 1s 737us/step - loss: 0.5439 - accuracy: 0.7325
Epoch 26/50
804/804 [==============================] - 1s 736us/step - loss: 0.5422 - accuracy: 0.7331
Epoch 27/50
804/804 [==============================] - 1s 738us/step - loss: 0.5394 - accuracy: 0.7346
Epoch 28/50
804/804 [==============================] - 1s 734us/step - loss: 0.5407 - accuracy: 0.7335
Epoch 29/50
804/804 [==============================] - 1s 762us/step - loss: 0.5381 - accuracy: 0.7355
Epoch 30/50
804/804 [==============================] - 1s 968us/step - loss: 0.5392 - accuracy: 0.7368
Epoch 31/50
804/804 [==============================] - 1s 817us/step - loss: 0.5377 - accuracy: 0.7386
Epoch 32/50
804/804 [==============================] - 1s 760us/step - loss: 0.5375 - accuracy: 0.7366
Epoch 33/50
804/804 [==============================] - 1s 759us/step - loss: 0.5403 - accuracy: 0.7357
Epoch 34/50
804/804 [==============================] - 1s 758us/step - loss: 0.5460 - accuracy: 0.7303
Epoch 35/50
804/804 [==============================] - 1s 754us/step - loss: 0.5339 - accuracy: 0.7380
Epoch 36/50
804/804 [==============================] - 1s 785us/step - loss: 0.5357 - accuracy: 0.7396
Epoch 37/50
804/804 [==============================] - 1s 773us/step - loss: 0.5391 - accuracy: 0.7366
Epoch 38/50
804/804 [==============================] - 1s 766us/step - loss: 0.5369 - accuracy: 0.7380
Epoch 39/50
804/804 [==============================] - 1s 778us/step - loss: 0.5413 - accuracy: 0.7333
Epoch 40/50
804/804 [==============================] - 1s 989us/step - loss: 0.5427 - accuracy: 0.7311
Epoch 41/50
804/804 [==============================] - 1s 872us/step - loss: 0.5376 - accuracy: 0.7376
Epoch 42/50
804/804 [==============================] - 1s 782us/step - loss: 0.5357 - accuracy: 0.7368
Epoch 43/50
804/804 [==============================] - 1s 750us/step - loss: 0.5387 - accuracy: 0.7331
Epoch 44/50
804/804 [==============================] - 1s 750us/step - loss: 0.5351 - accuracy: 0.7360
Epoch 45/50
804/804 [==============================] - 1s 829us/step - loss: 0.5393 - accuracy: 0.7354
Epoch 46/50
804/804 [==============================] - 1s 888us/step - loss: 0.5452 - accuracy: 0.7312
Epoch 47/50
804/804 [==============================] - 1s 735us/step - loss: 0.5329 - accuracy: 0.7391
Epoch 48/50
804/804 [==============================] - 1s 743us/step - loss: 0.5374 - accuracy: 0.7396
Epoch 49/50
804/804 [==============================] - 1s 725us/step - loss: 0.5337 - accuracy: 0.7400
Epoch 50/50
804/804 [==============================] - 1s 736us/step - loss: 0.5336 - accuracy: 0.7383

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [40]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5524 - accuracy: 0.7289
Loss: 0.5524492263793945, Accuracy: 0.728863000869751

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [41]:
# Set the model's file path
file_path = Path("Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [42]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [43]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 2

In [44]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (number_input_features + number_output_neurons_A1) // 3 

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

39

In [45]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [46]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))


# Output layer
nn_A1.add(Dense(units=1, activation="sigmoid"))


# Check the structure of the model

# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))


# Output layer
nn_A1.add(Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_2 (Dense)              (None, 39)                4563
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 40
_________________________________________________________________
dense_4 (Dense)              (None, 39)                78
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 40
=================================================================
Total params: 4,721
Trainable params: 4,721
Non-trainable params: 0
_________________________________________________________________

In [47]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [48]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 825us/step - loss: 0.6548 - accuracy: 0.6112
Epoch 2/100
804/804 [==============================] - 1s 876us/step - loss: 0.5780 - accuracy: 0.7310
Epoch 3/100
804/804 [==============================] - 1s 851us/step - loss: 0.5695 - accuracy: 0.7301
Epoch 4/100
804/804 [==============================] - 1s 930us/step - loss: 0.5683 - accuracy: 0.7326
Epoch 5/100
804/804 [==============================] - 1s 933us/step - loss: 0.5539 - accuracy: 0.7390
Epoch 6/100
804/804 [==============================] - 1s 816us/step - loss: 0.5514 - accuracy: 0.7393
Epoch 7/100
804/804 [==============================] - 1s 797us/step - loss: 0.5588 - accuracy: 0.7269
Epoch 8/100
804/804 [==============================] - 1s 775us/step - loss: 0.5457 - accuracy: 0.7383
Epoch 9/100
804/804 [==============================] - 1s 771us/step - loss: 0.5480 - accuracy: 0.7335
Epoch 10/100
804/804 [==============================] - 1s 771us/step - loss: 0.5523 - accuracy: 0.7306
Epoch 11/100
804/804 [==============================] - 1s 774us/step - loss: 0.5485 - accuracy: 0.7360
Epoch 12/100
804/804 [==============================] - 1s 770us/step - loss: 0.5480 - accuracy: 0.7344
Epoch 13/100
804/804 [==============================] - 1s 774us/step - loss: 0.5507 - accuracy: 0.7359
Epoch 14/100
804/804 [==============================] - 1s 776us/step - loss: 0.5471 - accuracy: 0.7364
Epoch 15/100
804/804 [==============================] - 1s 774us/step - loss: 0.5488 - accuracy: 0.7343
Epoch 16/100
804/804 [==============================] - 1s 783us/step - loss: 0.5479 - accuracy: 0.7326
Epoch 17/100
804/804 [==============================] - 1s 787us/step - loss: 0.5476 - accuracy: 0.7341
Epoch 18/100
804/804 [==============================] - 1s 790us/step - loss: 0.5519 - accuracy: 0.7308
Epoch 19/100
804/804 [==============================] - 1s 892us/step - loss: 0.5437 - accuracy: 0.7392
Epoch 20/100
804/804 [==============================] - 1s 847us/step - loss: 0.5443 - accuracy: 0.7369
Epoch 21/100
804/804 [==============================] - 1s 812us/step - loss: 0.5461 - accuracy: 0.7328
Epoch 22/100
804/804 [==============================] - 1s 782us/step - loss: 0.5422 - accuracy: 0.7396
Epoch 23/100
804/804 [==============================] - 1s 790us/step - loss: 0.5372 - accuracy: 0.7421
Epoch 24/100
804/804 [==============================] - 1s 793us/step - loss: 0.5408 - accuracy: 0.7346
Epoch 25/100
804/804 [==============================] - 1s 806us/step - loss: 0.5436 - accuracy: 0.7351
Epoch 26/100
804/804 [==============================] - 1s 796us/step - loss: 0.5379 - accuracy: 0.7417
Epoch 27/100
804/804 [==============================] - 1s 935us/step - loss: 0.5470 - accuracy: 0.7340
Epoch 28/100
804/804 [==============================] - 1s 927us/step - loss: 0.5424 - accuracy: 0.7371
Epoch 29/100
804/804 [==============================] - 1s 830us/step - loss: 0.5415 - accuracy: 0.7368
Epoch 30/100
804/804 [==============================] - 1s 805us/step - loss: 0.5397 - accuracy: 0.7384
Epoch 31/100
804/804 [==============================] - 1s 792us/step - loss: 0.5466 - accuracy: 0.7330
Epoch 32/100
804/804 [==============================] - 1s 794us/step - loss: 0.5403 - accuracy: 0.7385
Epoch 33/100
804/804 [==============================] - 1s 802us/step - loss: 0.5414 - accuracy: 0.7381
Epoch 34/100
804/804 [==============================] - 1s 830us/step - loss: 0.5354 - accuracy: 0.7457
Epoch 35/100
804/804 [==============================] - 1s 801us/step - loss: 0.5480 - accuracy: 0.7331
Epoch 36/100
804/804 [==============================] - 1s 802us/step - loss: 0.5430 - accuracy: 0.7344
Epoch 37/100
804/804 [==============================] - 1s 805us/step - loss: 0.5462 - accuracy: 0.7329
Epoch 38/100
804/804 [==============================] - 1s 795us/step - loss: 0.5404 - accuracy: 0.7382
Epoch 39/100
804/804 [==============================] - 1s 792us/step - loss: 0.5390 - accuracy: 0.7396
Epoch 40/100
804/804 [==============================] - 1s 924us/step - loss: 0.5421 - accuracy: 0.7360
Epoch 41/100
804/804 [==============================] - 1s 839us/step - loss: 0.5363 - accuracy: 0.7407
Epoch 42/100
804/804 [==============================] - 1s 803us/step - loss: 0.5392 - accuracy: 0.7384
Epoch 43/100
804/804 [==============================] - 1s 879us/step - loss: 0.5419 - accuracy: 0.7367
Epoch 44/100
804/804 [==============================] - 1s 891us/step - loss: 0.5375 - accuracy: 0.7411
Epoch 45/100
804/804 [==============================] - 1s 934us/step - loss: 0.5471 - accuracy: 0.7346
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7348
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7366
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7379
Epoch 49/100
804/804 [==============================] - 1s 975us/step - loss: 0.5389 - accuracy: 0.7430
Epoch 50/100
804/804 [==============================] - 1s 972us/step - loss: 0.5412 - accuracy: 0.7362
Epoch 51/100
804/804 [==============================] - 1s 930us/step - loss: 0.5369 - accuracy: 0.7379
Epoch 52/100
804/804 [==============================] - 1s 948us/step - loss: 0.5347 - accuracy: 0.7443
Epoch 53/100
804/804 [==============================] - 1s 822us/step - loss: 0.5432 - accuracy: 0.7361
Epoch 54/100
804/804 [==============================] - 1s 815us/step - loss: 0.5424 - accuracy: 0.7390
Epoch 55/100
804/804 [==============================] - 1s 919us/step - loss: 0.5377 - accuracy: 0.7397
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7382
Epoch 57/100
804/804 [==============================] - 1s 871us/step - loss: 0.5445 - accuracy: 0.7358
Epoch 58/100
804/804 [==============================] - 1s 894us/step - loss: 0.5428 - accuracy: 0.7364
Epoch 59/100
804/804 [==============================] - 1s 885us/step - loss: 0.5403 - accuracy: 0.7377
Epoch 60/100
804/804 [==============================] - 1s 798us/step - loss: 0.5417 - accuracy: 0.7382
Epoch 61/100
804/804 [==============================] - 1s 791us/step - loss: 0.5401 - accuracy: 0.7395
Epoch 62/100
804/804 [==============================] - 1s 788us/step - loss: 0.5390 - accuracy: 0.7408
Epoch 63/100
804/804 [==============================] - 1s 834us/step - loss: 0.5478 - accuracy: 0.7301
Epoch 64/100
804/804 [==============================] - 1s 821us/step - loss: 0.5396 - accuracy: 0.7365
Epoch 65/100
804/804 [==============================] - 1s 916us/step - loss: 0.5389 - accuracy: 0.7381
Epoch 66/100
804/804 [==============================] - 1s 955us/step - loss: 0.5402 - accuracy: 0.7362
Epoch 67/100
804/804 [==============================] - 1s 926us/step - loss: 0.5358 - accuracy: 0.7424
Epoch 68/100
804/804 [==============================] - 1s 918us/step - loss: 0.5359 - accuracy: 0.7401
Epoch 69/100
804/804 [==============================] - 1s 771us/step - loss: 0.5429 - accuracy: 0.7360
Epoch 70/100
804/804 [==============================] - 1s 784us/step - loss: 0.5397 - accuracy: 0.7380
Epoch 71/100
804/804 [==============================] - 1s 775us/step - loss: 0.5424 - accuracy: 0.7364
Epoch 72/100
804/804 [==============================] - 1s 838us/step - loss: 0.5425 - accuracy: 0.7374
Epoch 73/100
804/804 [==============================] - 1s 762us/step - loss: 0.5429 - accuracy: 0.7370
Epoch 74/100
804/804 [==============================] - 1s 923us/step - loss: 0.5372 - accuracy: 0.7397
Epoch 75/100
804/804 [==============================] - 1s 813us/step - loss: 0.5397 - accuracy: 0.7389
Epoch 76/100
804/804 [==============================] - 1s 782us/step - loss: 0.5392 - accuracy: 0.7399
Epoch 77/100
804/804 [==============================] - 1s 917us/step - loss: 0.5392 - accuracy: 0.7408
Epoch 78/100
804/804 [==============================] - 1s 811us/step - loss: 0.5346 - accuracy: 0.7421
Epoch 79/100
804/804 [==============================] - 1s 806us/step - loss: 0.5329 - accuracy: 0.7421
Epoch 80/100
804/804 [==============================] - 1s 810us/step - loss: 0.5405 - accuracy: 0.7372
Epoch 81/100
804/804 [==============================] - 1s 807us/step - loss: 0.5398 - accuracy: 0.7386
Epoch 82/100
804/804 [==============================] - 1s 807us/step - loss: 0.5352 - accuracy: 0.7401
Epoch 83/100
804/804 [==============================] - 1s 948us/step - loss: 0.5373 - accuracy: 0.7386
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7380
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7363
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7389
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7363
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7403
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7358
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7408
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7398
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5363 - accuracy: 0.7394
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7390
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7390
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7423
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7376
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7316
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7371
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7385
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5359 - accuracy: 0.7410

#### Alternative Model 2

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 3

In [49]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 74

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

74

In [52]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A2 = 30


# Review the number of hidden nodes in the first layer
hidden_nodes_layer2_A2

30

In [53]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [54]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu"))

# Output layer
nn.add(Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 74)                8658
=================================================================
Total params: 8,658
Trainable params: 8,658
Non-trainable params: 0
_________________________________________________________________

In [55]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [56]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=80)

Epoch 1/80
804/804 [==============================] - 1s 1ms/step - loss: 3.7354 - accuracy: 0.0016
Epoch 2/80
804/804 [==============================] - 1s 1ms/step - loss: 2.4075 - accuracy: 0.0251
Epoch 3/80
804/804 [==============================] - 1s 2ms/step - loss: 2.1136 - accuracy: 5.3428e-04
Epoch 4/80
804/804 [==============================] - 1s 2ms/step - loss: 1.9845 - accuracy: 0.0021
Epoch 5/80
804/804 [==============================] - 1s 1ms/step - loss: 1.8335 - accuracy: 9.6690e-04
Epoch 6/80
804/804 [==============================] - 1s 2ms/step - loss: 1.8057 - accuracy: 6.2623e-06
Epoch 7/80
804/804 [==============================] - 1s 2ms/step - loss: 1.7701 - accuracy: 7.7733e-05
Epoch 8/80
804/804 [==============================] - 1s 2ms/step - loss: 1.7761 - accuracy: 0.0376
Epoch 9/80
804/804 [==============================] - 1s 2ms/step - loss: 1.7292 - accuracy: 0.0239
Epoch 10/80
804/804 [==============================] - 1s 2ms/step - loss: 1.7167 - accuracy: 0.0025: 0s
Epoch 11/80
804/804 [==============================] - 1s 2ms/step - loss: 1.7065 - accuracy: 0.0013
Epoch 12/80
804/804 [==============================] - 1s 2ms/step - loss: 1.6983 - accuracy: 0.0021
Epoch 13/80
804/804 [==============================] - 1s 1ms/step - loss: 1.7010 - accuracy: 1.1674e-04
Epoch 14/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6662 - accuracy: 0.0017
Epoch 15/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6428 - accuracy: 0.0014
Epoch 16/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6469 - accuracy: 3.8329e-04
Epoch 17/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6696 - accuracy: 5.6726e-04
Epoch 18/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6583 - accuracy: 0.0014
Epoch 19/80
804/804 [==============================] - 1s 2ms/step - loss: 1.6549 - accuracy: 0.0201
Epoch 20/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6460 - accuracy: 0.0033
Epoch 21/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6555 - accuracy: 2.2037e-04
Epoch 22/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6365 - accuracy: 8.3152e-04
Epoch 23/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6168 - accuracy: 3.7601e-04
Epoch 24/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6278 - accuracy: 0.0749
Epoch 25/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6231 - accuracy: 0.0842
Epoch 26/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6092 - accuracy: 0.0552
Epoch 27/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6066 - accuracy: 1.9718e-04
Epoch 28/80
804/804 [==============================] - 1s 2ms/step - loss: 1.6137 - accuracy: 2.6358e-05
Epoch 29/80
804/804 [==============================] - 1s 2ms/step - loss: 1.6215 - accuracy: 1.6600e-04
Epoch 30/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6131 - accuracy: 3.0977e-04
Epoch 31/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6124 - accuracy: 0.0093
Epoch 32/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5829 - accuracy: 0.0032
Epoch 33/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6112 - accuracy: 0.0131
Epoch 34/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5897 - accuracy: 9.8803e-04
Epoch 35/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6063 - accuracy: 0.0030
Epoch 36/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5954 - accuracy: 0.0307
Epoch 37/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5944 - accuracy: 7.0282e-04
Epoch 38/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6110 - accuracy: 2.2756e-04
Epoch 39/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5841 - accuracy: 7.0998e-04
Epoch 40/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5898 - accuracy: 2.7550e-04
Epoch 41/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5880 - accuracy: 5.6131e-04
Epoch 42/80
804/804 [==============================] - 2s 2ms/step - loss: 1.5889 - accuracy: 0.0044
Epoch 43/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5901 - accuracy: 0.0052
Epoch 44/80
804/804 [==============================] - 1s 2ms/step - loss: 1.6062 - accuracy: 0.0057
Epoch 45/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5977 - accuracy: 0.0039
Epoch 46/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5877 - accuracy: 0.0029
Epoch 47/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5530 - accuracy: 0.0175
Epoch 48/80
804/804 [==============================] - 1s 2ms/step - loss: 1.6096 - accuracy: 0.0178
Epoch 49/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5870 - accuracy: 5.9638e-04
Epoch 50/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6045 - accuracy: 0.0067
Epoch 51/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5748 - accuracy: 0.0187
Epoch 52/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5981 - accuracy: 0.0076
Epoch 53/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5885 - accuracy: 0.0015
Epoch 54/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5643 - accuracy: 0.0029
Epoch 55/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6065 - accuracy: 0.0079
Epoch 56/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5780 - accuracy: 0.0242
Epoch 57/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5851 - accuracy: 0.0102
Epoch 58/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5972 - accuracy: 0.0028
Epoch 59/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5802 - accuracy: 9.2371e-04
Epoch 60/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5745 - accuracy: 7.4007e-04
Epoch 61/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5931 - accuracy: 0.0043
Epoch 62/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5610 - accuracy: 0.0011
Epoch 63/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5824 - accuracy: 0.0022
Epoch 64/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5896 - accuracy: 0.0038
Epoch 65/80
804/804 [==============================] - 1s 1ms/step - loss: 1.6175 - accuracy: 0.0040
Epoch 66/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5918 - accuracy: 0.0151
Epoch 67/80
804/804 [==============================] - 2s 2ms/step - loss: 1.5701 - accuracy: 1.7015e-04
Epoch 68/80
804/804 [==============================] - 2s 2ms/step - loss: 1.5737 - accuracy: 0.0037
Epoch 69/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5650 - accuracy: 0.0016
Epoch 70/80
804/804 [==============================] - 2s 2ms/step - loss: 1.5686 - accuracy: 0.0086
Epoch 71/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5669 - accuracy: 0.0043
Epoch 72/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5699 - accuracy: 0.0021
Epoch 73/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5425 - accuracy: 0.1139
Epoch 74/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5785 - accuracy: 0.0323
Epoch 75/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5546 - accuracy: 0.0042
Epoch 76/80
804/804 [==============================] - 1s 1ms/step - loss: 1.5702 - accuracy: 0.0048
Epoch 77/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5743 - accuracy: 0.0172
Epoch 78/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5655 - accuracy: 0.0068
Epoch 79/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5674 - accuracy: 0.0038
Epoch 80/80
804/804 [==============================] - 1s 2ms/step - loss: 1.5732 - accuracy: 0.0029

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [57]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5524 - accuracy: 0.7289
Loss: 0.5524492263793945, Accuracy: 0.728863000869751

In [58]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5519 - accuracy: 0.7292
Loss: 0.5518993735313416, Accuracy: 0.7292128205299377

In [59]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 1.5213 - accuracy: 0.0000e+00
Loss: 1.5212891101837158, Accuracy: 0.0

### Step 3: Save each of your alternative models as an HDF5 file.

In [66]:
# Set the file path for the first alternative model
file_path = Path("Resources/AlphabetSoupA1.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [65]:
# Set the file path for the second alternative model
file_path = Path("Resources/AlphabetSoupA2.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)